### ISSUE TITLE
How can I output an uncompressed address?

### ISSUE THREAD

**Issue by Gusev39rus** [karask/python-litecoin-utils#4]
```
# print the address and hash160 - default is compressed address
    print("Address:", address.to_string())
```
How can I output an uncompressed address?

**Comment by karask** [comment]
When you get an address object from a public key object is when you specify if it is compressed or not. The comment might be confusing there because it actually refers to the public key.

compressed_address = pub.get_address()
uncompressed_address = pub.get_address(compressed=False)

print("Compressed: ", compressed_address.to_string())
print("Uncompressed: ", uncompressed_address.to_string())
